// RFC 9462 Designated Resolver Discovery state owner. One resolver and one
// network identity own one instance, preventing a designation learned from
// one unencrypted resolver or network from leaking into another context.

#pragma once

#include "router/dns_packet.hpp"
#include "router/ip_address.hpp"

#include <array>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <optional>
#include <span>
#include <string>
#include <vector>

namespace router::ddr {

enum class AddressFamily : std::uint8_t { ipv4, ipv6 };

struct Address {
  AddressFamily family{AddressFamily::ipv4};
  // IPv4 uses the first four network-order octets and keeps the rest zero.
  // The fixed layout avoids variants and allocations in candidate lists.
  std::array<std::uint8_t, 16U> bytes{};

  [[nodiscard]] static Address ipv4(const ip::Ipv4 &value) noexcept;
  [[nodiscard]] static Address ipv6(const ip::Ipv6 &value) noexcept;
  [[nodiscard]] friend constexpr bool
  operator==(const Address &, const Address &) noexcept = default;
};

enum class DiscoveryMode : std::uint8_t { resolver_address, resolver_name };
enum class AutomaticPolicy : std::uint8_t {
  verified_only,
  verified_or_local_opportunistic,
  manual_only
};
enum class Protocol : std::uint8_t { dot, doq, doh2, doh3 };
enum class IngestResult : std::uint8_t {
  candidates_available,
  alias_followup_required,
  no_designated_resolver,
  malformed_rrset,
  alias_limit,
  resource_exhausted
};
enum class ConfirmationResult : std::uint8_t {
  usable,
  rejected_authentication,
  rejected_policy,
  invalid_candidate
};

struct Configuration {
  DiscoveryMode mode{DiscoveryMode::resolver_address};
  Address unencrypted_resolver{};
  packet::dns::Name known_resolver_name{};
  std::uint64_t network_identity{};
  AutomaticPolicy automatic_policy{AutomaticPolicy::verified_only};
  // The nonce is generated by the project CSPRNG and persisted with an active
  // discovery. It randomizes equal-priority alternatives without a global RNG.
  std::uint64_t selection_nonce{};
  std::size_t max_alias_depth{};
  std::size_t max_candidates{};
  std::size_t max_addresses_per_candidate{};
  std::size_t max_parameters_per_record{};
};

struct Endpoint {
  std::uint16_t priority{};
  packet::dns::Name target;
  Protocol protocol{Protocol::dot};
  std::uint16_t port{};
  std::string doh_uri_template;
  std::vector<Address> addresses;
  bool usable{};
};

struct AuthenticationEvidence {
  bool certificate_chain_valid{};
  bool original_resolver_ip_in_subject_alt_name{};
  bool known_resolver_name_in_subject_alt_name{};
  Address connected_address{};
  bool manual_approval{};
};

class Discovery final {
public:
  // Configuration is rejected if limits are zero, the known name is invalid,
  // or a resolver-address discovery uses an unusable source address. The
  // returned owner has no dependency on sockets, UI state or other devices.
  [[nodiscard]] static std::optional<Discovery>
  create(Configuration configuration) noexcept;

  Discovery(Discovery &&) noexcept;
  Discovery &operator=(Discovery &&) noexcept;
  Discovery(const Discovery &) = delete;
  Discovery &operator=(const Discovery &) = delete;
  ~Discovery();

  // The caller sends a type-64 DNS query for this exact name through its
  // configured resolver. AliasMode updates the name and returns a follow-up
  // result. No DNS request is sent directly by this policy owner.
  [[nodiscard]] const packet::dns::Name &query_name() const noexcept;

  // Answers and additionals must already be canonical, owned RecordData from
  // one complete DNS response. Publication is transactional: malformed input
  // leaves no candidates. At most the configured limits are retained.
  [[nodiscard]] IngestResult
  ingest(std::span<const packet::dns::RecordData> answers,
         std::span<const packet::dns::RecordData> additionals) noexcept;

  // TLS or QUIC/TLS performs cryptographic verification and reports evidence.
  // This policy owner enforces the RFC 9462 binding to the original resolver
  // address or name before marking an endpoint usable.
  [[nodiscard]] ConfirmationResult
  confirm(std::size_t candidate_index,
          const AuthenticationEvidence &evidence) noexcept;

  [[nodiscard]] std::span<const Endpoint> candidates() const noexcept;
  [[nodiscard]] std::uint64_t network_identity() const noexcept;

private:
  struct Impl;
  explicit Discovery(std::unique_ptr<Impl> implementation) noexcept;
  std::unique_ptr<Impl> implementation_;
};

} // namespace router::ddr
