// Independent module-test entry point. It links no runtime coordinator or Wasm
// ABI, proving hardware, forwarding and checkpoint boundaries are testable
// alone.

#include <iostream>
#include <stdexcept>

void capture_store_tests();
void dhcpv6_client_tests();
void dhcpv6_lease_tests();
void dhcpv6_packet_tests();
void dhcpv6_relay_tests();
void dhcpv6_relay_lease_tests();
void dhcpv6_relay_route_tests();
void dhcpv6_retransmission_tests();
void dhcpv6_server_tests();
void dns_packet_tests();
void ddr_discovery_tests();
void dns_authoritative_tests();
void dns_cache_tests();
void dns_master_file_tests();
void dns_resolver_tests();
void dnssec_record_tests();
void dnssec_validation_tests();
void dnssec_chain_tests();
void dnssec_denial_tests();
void ethernet_switch_tests();
#ifdef __EMSCRIPTEN__
void ikev2_aes_gcm_tests();
void ikev2_encrypted_payload_tests();
void ikev2_dh_tests();
void ikev2_nat_detection_tests();
void ipsec_esp_processor_tests();
void ipsec_esp_gcm_tests();
void dnssec_openssl_tests();
void dnssec_signer_tests();
void dnssec_zone_signer_tests();
void dnssec_key_lifecycle_tests();
void dnssec_nsec_chain_tests();
void dnssec_nsec3_chain_tests();
void dnssec_authoritative_response_tests();
void dnssec_response_validation_tests();
void dnssec_zone_keys_tests();
void dnssec_signed_zone_tests();
void dnssec_signed_zone_owner_tests();
#endif
void dns_endpoint_service_tests();
void hardware_tests();
void lab_registry_tests();
void multi_device_fabric_tests();
void multi_device_routing_tests();
void ipv4_reassembly_tests();
void ipv6_dad_tests();
void ipv6_extension_tests();
void ipv6_fragmentation_tests();
void ipv6_destination_cache_tests();
void ipv6_host_autoconfiguration_tests();
void icmpv4_statistics_tests();
void icmpv6_statistics_tests();
void ies_service_tests();
void ies_cli_configuration_tests();
void ipv6_path_mtu_tests();
void ipv4_path_mtu_tests();
void ipv6_neighbor_cache_tests();
void ipv6_router_advertisement_tests();
void ipv6_source_selection_tests();
void router_ipv6_address_table_tests();
void ipv6_stable_iid_tests();
void ikev2_packet_tests();
void ikev2_authentication_tests();
void ikev2_exchange_tests();
void ikev2_fragmentation_tests();
void ikev2_kdf_tests();
void ikev2_negotiation_tests();
void ikev2_payload_tests();
void ikev2_payload_data_tests();
void ikev2_peer_path_tests();
void ikev2_profile_tests();
void ikev2_sa_tests();
void ikev2_session_service_tests();
void ikev2_udp_service_tests();
void ipsec_tests();
void ipsec_ah_canonical_tests();
void ipsec_ah_processor_tests();
void ipsec_lifetime_tests();
void ipsec_integrity_tests();
void ipsec_cli_configuration_tests();
void ipsec_nat_t_tests();
void mld_packet_tests();
void mld_import_policy_tests();
void mld_listener_tests();
void mld_router_tests();
void ospf_fsm_tests();
void ospf_area_coordinator_tests();
void ospf_configuration_tests();
void ospf_cli_configuration_tests();
void ospf_interface_tests();
void ospf_database_exchange_tests();
void ospf_lsdb_tests();
void ospf_lsa_tests();
void ospf_lsa_builder_tests();
void ospf_packet_tests();
void ospf_authentication_tests();
void ospf_keychain_tests();
void ospf_process_address_family_tests();
void ospf_process_authentication_tests();
void ospf_process_broadcast_tests();
void ospf_process_point_to_point_tests();
void ospf_process_restart_tests();
void ospf_route_calculator_tests();
void ospf_packet_channel_tests();
void ospf_route_channel_tests();
void ospf_spf_tests();
void ospf_topology_tests();
void route_policy_tests();
void network_endpoint_ipv4_tests();
void network_endpoint_ipv6_tests();
void network_plane_tests();
void routing_tests();
void router_hardware_inventory_tests();
void router_forwarder_local_ipv4_delivery_tests();
void router_forwarder_ospfv3_multicast_tests();
void router_forwarder_ipv4_redirect_tests();
void router_forwarder_tests();
void sap_forwarding_tests();
void session_workflow_tests();
void shard_policy_tests();
void tcp_packet_tests();
void tcp_congestion_tests();
void tcp_connection_tests();
void tcp_endpoint_tests();
void tcp_control_block_tests();
void tcp_failure_tests();
void tcp_isn_tests();
void tcp_options_tests();
void tcp_receive_buffer_tests();
void tcp_receive_window_tests();
void tcp_retransmission_tests();
void tcp_sack_scoreboard_tests();
void tcp_send_buffer_tests();
void tcp_sender_tests();
void tcp_timers_tests();
void tcp_transmission_history_tests();
void tcp_sequence_tests();
void udp_packet_tests();
void udp_transport_tests();
#ifdef __EMSCRIPTEN__
void secret_vault_tests();
void pki_store_tests();
void tls_engine_tests();
void tls_profile_tests();
void http2_session_tests();
void dot_session_tests();
void doh2_session_tests();
void quic_connection_tests();
void http3_session_tests();
#endif

int main() {
  try {
    // Run low-level suites in dependency order. A thrown failure stops before a
    // higher layer can obscure which standalone contract was violated.
    capture_store_tests();
    dhcpv6_client_tests();
    dhcpv6_lease_tests();
    dhcpv6_packet_tests();
    dhcpv6_relay_tests();
    dhcpv6_relay_lease_tests();
    dhcpv6_relay_route_tests();
    dhcpv6_retransmission_tests();
    dhcpv6_server_tests();
    dns_packet_tests();
    ddr_discovery_tests();
    dns_authoritative_tests();
    dns_cache_tests();
    dns_master_file_tests();
    dns_resolver_tests();
    dnssec_record_tests();
    dnssec_validation_tests();
    dnssec_chain_tests();
    dnssec_denial_tests();
    ethernet_switch_tests();
#ifdef __EMSCRIPTEN__
    secret_vault_tests();
    ikev2_aes_gcm_tests();
    ikev2_encrypted_payload_tests();
    ikev2_dh_tests();
    ikev2_nat_detection_tests();
    ipsec_esp_processor_tests();
    ipsec_esp_gcm_tests();
    dnssec_openssl_tests();
    dnssec_signer_tests();
    dnssec_zone_signer_tests();
    dnssec_key_lifecycle_tests();
    dnssec_nsec_chain_tests();
    dnssec_nsec3_chain_tests();
    dnssec_authoritative_response_tests();
    dnssec_response_validation_tests();
    dnssec_zone_keys_tests();
    dnssec_signed_zone_tests();
    dnssec_signed_zone_owner_tests();
    pki_store_tests();
    tls_engine_tests();
    tls_profile_tests();
    http2_session_tests();
    dot_session_tests();
    doh2_session_tests();
    quic_connection_tests();
    http3_session_tests();
#endif
    dns_endpoint_service_tests();
    // Legacy behavior stays executable until the catalog-backed inventories
    // pass the same lifecycle, alarm and routing assertions per router.
    hardware_tests();
    lab_registry_tests();
    multi_device_fabric_tests();
    multi_device_routing_tests();
    ipv4_reassembly_tests();
    ipv6_dad_tests();
    ipv6_extension_tests();
    ipv6_fragmentation_tests();
    ipv6_destination_cache_tests();
    ipv6_host_autoconfiguration_tests();
    icmpv4_statistics_tests();
    icmpv6_statistics_tests();
    ies_service_tests();
    ies_cli_configuration_tests();
    ipv4_path_mtu_tests();
    ipv6_path_mtu_tests();
    ipv6_neighbor_cache_tests();
    ipv6_router_advertisement_tests();
    ipv6_source_selection_tests();
    router_ipv6_address_table_tests();
    ipv6_stable_iid_tests();
    ikev2_packet_tests();
    ikev2_authentication_tests();
    ikev2_exchange_tests();
    ikev2_fragmentation_tests();
    ikev2_kdf_tests();
    ikev2_negotiation_tests();
    ikev2_payload_tests();
    ikev2_payload_data_tests();
    ikev2_peer_path_tests();
    ikev2_profile_tests();
    ikev2_sa_tests();
    ikev2_session_service_tests();
    ikev2_udp_service_tests();
    ipsec_tests();
    ipsec_cli_configuration_tests();
    ipsec_ah_canonical_tests();
    ipsec_ah_processor_tests();
    ipsec_lifetime_tests();
    ipsec_integrity_tests();
    ipsec_nat_t_tests();
    mld_packet_tests();
    mld_import_policy_tests();
    mld_listener_tests();
    mld_router_tests();
    ospf_fsm_tests();
    ospf_area_coordinator_tests();
    ospf_configuration_tests();
    ospf_cli_configuration_tests();
    ospf_interface_tests();
    ospf_database_exchange_tests();
    ospf_lsdb_tests();
    ospf_lsa_tests();
    ospf_lsa_builder_tests();
    ospf_packet_tests();
    ospf_authentication_tests();
    ospf_keychain_tests();
    ospf_process_authentication_tests();
    ospf_process_point_to_point_tests();
    ospf_process_broadcast_tests();
    ospf_process_address_family_tests();
    ospf_process_restart_tests();
    ospf_route_calculator_tests();
    ospf_packet_channel_tests();
    ospf_route_channel_tests();
    ospf_spf_tests();
    ospf_topology_tests();
    route_policy_tests();
    network_endpoint_ipv4_tests();
    network_endpoint_ipv6_tests();
    network_plane_tests();
    routing_tests();
    router_hardware_inventory_tests();
    router_forwarder_local_ipv4_delivery_tests();
    router_forwarder_ospfv3_multicast_tests();
    router_forwarder_ipv4_redirect_tests();
    router_forwarder_tests();
    sap_forwarding_tests();
    session_workflow_tests();
    shard_policy_tests();
    tcp_packet_tests();
    tcp_congestion_tests();
    tcp_connection_tests();
    tcp_endpoint_tests();
    tcp_control_block_tests();
    tcp_failure_tests();
    tcp_isn_tests();
    tcp_options_tests();
    tcp_receive_buffer_tests();
    tcp_receive_window_tests();
    tcp_retransmission_tests();
    tcp_sack_scoreboard_tests();
    tcp_send_buffer_tests();
    tcp_sender_tests();
    tcp_timers_tests();
    tcp_transmission_history_tests();
    tcp_sequence_tests();
    udp_packet_tests();
    udp_transport_tests();
    std::cout << "module tests passed\n";
    return 0;
  } catch (const std::exception &error) {
    // CTest treats the nonzero exit as failure and preserves the focused module
    // diagnostic written by the suite that detected the broken invariant.
    std::cerr << error.what() << '\n';
    return 1;
  }
}
