# Generated from profiles/catalog/26.7.R1.yaml. Do not edit.
set(ROUTER_WASM_STACK_BYTES 1048576)
set(ROUTER_LOGICAL_CPU_LOW_MAX 4)
set(ROUTER_LOGICAL_CPU_MEDIUM_MAX 8)
set(ROUTER_PTHREAD_POOL_LOW 1)
set(ROUTER_PTHREAD_POOL_MEDIUM 3)
set(ROUTER_PTHREAD_POOL_HIGH 5)
