// Integration tests pass RFC 8080's DNSKEY and the corrected RRSIG from
// verified erratum 4935 through the same canonical RRset path used by the
// resolver. The original RFC example counted the root label and is invalid.
// This proves the DNS wire conversion and linked OpenSSL provider rather than
// testing an EVP call against data generated by the same implementation.

#include "router/dnssec_openssl.hpp"
#include "router/dnssec_denial.hpp"

#include <openssl/evp.h>

#include <stdexcept>
#include <string>

namespace {

router::packet::dns::Name name(const char *text) {
  const auto parsed = router::packet::dns::name_from_text(text);
  if (!parsed)
    throw std::runtime_error("RFC 8080 fixture name is malformed");
  return *parsed;
}

std::vector<std::uint8_t> base64(std::string text) {
  if (text.empty() || text.size() % 4U != 0U)
    throw std::runtime_error("RFC 8080 fixture Base64 length is malformed");
  std::vector<std::uint8_t> decoded((text.size() / 4U) * 3U);
  const auto length = EVP_DecodeBlock(
      decoded.data(),
      reinterpret_cast<const unsigned char *>(text.data()),
      static_cast<int>(text.size()));
  if (length < 0)
    throw std::runtime_error("RFC 8080 fixture Base64 decoding failed");
  std::size_t padding{};
  if (text.ends_with("=="))
    padding = 2U;
  else if (text.ends_with('='))
    padding = 1U;
  decoded.resize(static_cast<std::size_t>(length) - padding);
  return decoded;
}

std::vector<std::uint8_t> hex(std::string text) {
  if (text.size() % 2U != 0U)
    throw std::runtime_error("RFC fixture hexadecimal length is malformed");
  const auto nibble = [](char value) -> std::uint8_t {
    if (value >= '0' && value <= '9')
      return static_cast<std::uint8_t>(value - '0');
    if (value >= 'a' && value <= 'f')
      return static_cast<std::uint8_t>(10 + value - 'a');
    throw std::runtime_error("RFC fixture contains non-hexadecimal data");
  };
  std::vector<std::uint8_t> output;
  output.reserve(text.size() / 2U);
  for (std::size_t index{}; index < text.size(); index += 2U)
    output.push_back(static_cast<std::uint8_t>(
        (nibble(text[index]) << 4U) | nibble(text[index + 1U])));
  return output;
}

std::string base32hex(std::span<const std::uint8_t> input) {
  static constexpr char alphabet[] = "0123456789abcdefghijklmnopqrstuv";
  std::string output;
  std::uint32_t bits{};
  unsigned count{};
  for (const auto octet : input) {
    bits = (bits << 8U) | octet;
    count += 8U;
    while (count >= 5U) {
      count -= 5U;
      output.push_back(alphabet[(bits >> count) & 0x1fU]);
      bits &= count == 0U ? 0U : (1U << count) - 1U;
    }
  }
  if (count != 0U)
    output.push_back(alphabet[(bits << (5U - count)) & 0x1fU]);
  return output;
}

} // namespace

void dnssec_openssl_tests() {
  using namespace router;

  const auto owner = name("example.com.");
  const auto exchange = name("mail.example.com.");
  std::vector<std::uint8_t> mx_rdata{0U, 10U};
  mx_rdata.insert(mx_rdata.end(), exchange.wire.begin(),
                  exchange.wire.begin() + exchange.octets);
  const dns::ZoneRecord mx{.owner = owner,
                           .type = packet::dns::type_mx,
                           .record_class = packet::dns::internet_class,
                           .ttl = 3600U,
                           .rdata = mx_rdata};

  dnssec::Dnskey key{.flags = 257U,
                     .protocol = dnssec::dnskey_protocol,
                     .algorithm = 15U,
                     .public_key = base64(
                         "l02Woi0iS8Aa25FQkUd9RMzZHJpBoRQwAQEX1SxZJA4=")};
  std::vector<std::uint8_t> key_wire;
  if (!dnssec::encode_dnskey(key, key_wire) ||
      dnssec::key_tag(key_wire) != 3613U)
    throw std::runtime_error("RFC 8080 DNSKEY codec or key tag drifted");

  dnssec::Rrsig signature{
      .type_covered = packet::dns::type_mx,
      .algorithm = 15U,
      .labels = 2U,
      .original_ttl = 3600U,
      .signature_expiration = 1440021600U,
      .signature_inception = 1438207200U,
      .key_tag = 3613U,
      .signer_name = owner,
      .signature = base64(
          "oL9krJun7xfBOIWcGHi7mag5/hdZrKWw15jPGrHpjQeRAvTdszaPD+QLs3fx8A4M3e23mRZ9VrbpMngwcrqNAg==")};
  std::vector<std::uint8_t> signed_data;
  if (!dnssec::canonical_signed_data(signature, std::span{&mx, 1U},
                                     signed_data))
    throw std::runtime_error("RFC 8080 RRset canonicalization failed");

  dnssec::OpenSslCryptoVerifier verifier;
  if (!verifier.supports(8U) || !verifier.supports(13U) ||
      !verifier.supports(15U) || verifier.supports(12U) ||
      !verifier.verify(15U, key.public_key, signed_data,
                       signature.signature))
    throw std::runtime_error("RFC 8080 Ed25519 signature was not verified");

  // The RFC 8080 DS value independently checks provider digest mapping and
  // the canonical owner plus full DNSKEY input required by RFC 4034.
  std::vector<std::uint8_t> ds_input(owner.wire.begin(),
                                     owner.wire.begin() + owner.octets);
  ds_input.insert(ds_input.end(), key_wire.begin(), key_wire.end());
  std::vector<std::uint8_t> sha256_digest;
  if (!verifier.supports_digest(1U) || !verifier.supports_digest(2U) ||
      !verifier.supports_digest(4U) || verifier.supports_digest(3U) ||
      !verifier.calculate_digest(2U, ds_input, sha256_digest) ||
      sha256_digest != hex(
          "3aa5ab37efce57f737fc1627013fee07bdf241bd10f3b1964ab55c78e79a304b"))
    throw std::runtime_error("RFC 8080 SHA-256 DS digest was not reproduced");
  std::vector<std::uint8_t> digest;
  if (!verifier.calculate_digest(1U, ds_input, digest) || digest.size() != 20U ||
      !verifier.calculate_digest(4U, ds_input, digest) || digest.size() != 48U)
    throw std::runtime_error("DNSSEC DS digest backend length is wrong");

  // RFC 5155 Appendix A publishes this NSEC3 SHA-1 hash. A policy allowing
  // twelve legacy iterations is explicit here; the RFC 9276 default remains
  // zero for production resolver configuration.
  dnssec::Nsec3 nsec3_parameters{.hash_algorithm = 1U,
                                 .flags = 1U,
                                 .iterations = 12U,
                                 .salt = hex("aabbccdd"),
                                 .next_hashed_owner =
                                     std::vector<std::uint8_t>(20U),
                                 .types = {packet::dns::type_nsec3}};
  std::vector<std::uint8_t> nsec3_digest;
  if (dnssec::nsec3_hash(name("example."), nsec3_parameters,
                         {.maximum = 12U}, verifier, nsec3_digest) !=
          dnssec::Nsec3ProofState::proved ||
      base32hex(nsec3_digest) != "0p9mhaveqvm6t7vbl5lop2u3t2rp3tom")
    throw std::runtime_error("RFC 5155 NSEC3 hash was not reproduced");

  auto tampered = signed_data;
  tampered.back() ^= 1U;
  if (verifier.verify(15U, key.public_key, tampered, signature.signature) ||
      verifier.verify(15U, std::span<const std::uint8_t>{}, signed_data,
                      signature.signature))
    throw std::runtime_error("OpenSSL DNSSEC verifier accepted malformed data");

  std::vector<std::uint8_t> signature_wire;
  if (!dnssec::encode_rrsig(signature, signature_wire))
    throw std::runtime_error("RFC 8080 RRSIG encoding failed");
  const dns::ZoneRecord signature_record{
      .owner = owner,
      .type = packet::dns::type_rrsig,
      .record_class = packet::dns::internet_class,
      .ttl = 3600U,
      .rdata = signature_wire};
  const dns::ZoneRecord key_record{.owner = owner,
                                   .type = packet::dns::type_dnskey,
                                   .record_class = packet::dns::internet_class,
                                   .ttl = 3600U,
                                   .rdata = key_wire};
  const auto result = dnssec::validate_rrset(
      std::span{&mx, 1U}, std::span{&signature_record, 1U},
      std::span{&key_record, 1U}, 1439000000U, verifier);
  if (result.state != dnssec::ValidationState::secure ||
      result.key_tag != 3613U)
    throw std::runtime_error("RFC 8080 signature failed resolver validation");

  // RFC 6605 section 6.1 publishes an independent P-256 DNSKEY and A RRset
  // signature. It exercises both fixed-coordinate key import and raw r|s to
  // ASN.1 conversion, neither of which the Ed25519 vector reaches.
  const auto ecdsa_owner = name("www.example.net.");
  const auto ecdsa_signer = name("example.net.");
  const dns::ZoneRecord ecdsa_record{
      .owner = ecdsa_owner,
      .type = packet::dns::type_a,
      .record_class = packet::dns::internet_class,
      .ttl = 3600U,
      .rdata = {192U, 0U, 2U, 1U}};
  dnssec::Dnskey ecdsa_key{
      .flags = 257U,
      .protocol = dnssec::dnskey_protocol,
      .algorithm = 13U,
      .public_key = base64(
          "GojIhhXUN/u4v54ZQqGSnyhWJwaubCvTmeexv7bR6edbkrSqQpF64cYbcB7wNcP+e+MAnLr+Wi9xMWyQLc8NAA==")};
  dnssec::Rrsig ecdsa_signature{
      .type_covered = packet::dns::type_a,
      .algorithm = 13U,
      .labels = 3U,
      .original_ttl = 3600U,
      .signature_expiration = 1284026679U,
      .signature_inception = 1281607479U,
      .key_tag = 55648U,
      .signer_name = ecdsa_signer,
      .signature = base64(
          "qx6wLYqmh+l9oCKTN6qIc+bw6ya+KJ8oMz0YP107epXAyGmt+3SNruPFKG7tZoLBLlUzGGus7ZwmwWep666VCw==")};
  std::vector<std::uint8_t> ecdsa_data;
  if (!dnssec::canonical_signed_data(ecdsa_signature,
                                     std::span{&ecdsa_record, 1U},
                                     ecdsa_data) ||
      !verifier.verify(13U, ecdsa_key.public_key, ecdsa_data,
                       ecdsa_signature.signature))
    throw std::runtime_error("RFC 6605 P-256 signature was not verified");

  // RFC 5702 section 6.1 covers the extended DNS RSA key encoding and
  // PKCS#1 v1.5 SHA-256 verification using a published 512-bit fixture.
  const auto rsa_owner = name("www.example.net.");
  const auto rsa_signer = name("example.net.");
  const dns::ZoneRecord rsa_record{
      .owner = rsa_owner,
      .type = packet::dns::type_a,
      .record_class = packet::dns::internet_class,
      .ttl = 3600U,
      .rdata = {192U, 0U, 2U, 91U}};
  dnssec::Dnskey rsa_key{
      .flags = 256U,
      .protocol = dnssec::dnskey_protocol,
      .algorithm = 8U,
      .public_key = base64(
          "AwEAAcFcGsaxxdgiuuGmCkVImy4h99CqT7jwY3pexPGcnUFtR2Fh36BponcwtkZ4cAgtvd4Qs8PkxUdp6p/DlUmObdk=")};
  dnssec::Rrsig rsa_signature{
      .type_covered = packet::dns::type_a,
      .algorithm = 8U,
      .labels = 3U,
      .original_ttl = 3600U,
      .signature_expiration = 1893456000U,
      .signature_inception = 946684800U,
      .key_tag = 9033U,
      .signer_name = rsa_signer,
      .signature = base64(
          "kRCOH6u7l0QGy9qpC9l1sLncJcOKFLJ7GhiUOibu4teYp5VE9RncriShZNz85mwlMgNEacFYK/lPtPiVYP4bwg==")};
  std::vector<std::uint8_t> rsa_data;
  if (!dnssec::canonical_signed_data(rsa_signature,
                                     std::span{&rsa_record, 1U}, rsa_data) ||
      !verifier.verify(8U, rsa_key.public_key, rsa_data,
                       rsa_signature.signature))
    throw std::runtime_error("RFC 5702 RSA/SHA-256 signature was not verified");

  auto leading_zero_rsa = rsa_key.public_key;
  leading_zero_rsa.insert(leading_zero_rsa.begin() + 4, 0U);
  leading_zero_rsa[0] = 4U;
  if (verifier.verify(8U, leading_zero_rsa, rsa_data,
                      rsa_signature.signature))
    throw std::runtime_error("DNSSEC RSA accepted a leading-zero exponent");
}
